<Project Sdk="Godot.NET.Sdk/4.7.2">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CardGameCore.Test\CardGameCore.Test.csproj" />
    <ProjectReference Include="..\CardGameCore\CardGameCore.csproj" />
  </ItemGroup>
</Project>